spring.application.name=API-GATEWAY

server.port=8787

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Explicit Routes for Microservices
spring.cloud.gateway.routes[0].id=questionservice
spring.cloud.gateway.routes[0].uri=lb://QUESTIONSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/question/**

spring.cloud.gateway.routes[1].id=quizservice
spring.cloud.gateway.routes[1].uri=lb://QUIZSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/quiz/**

# Global CORS Configuration (Allows Frontend React at http://localhost:5173)
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

management.endpoints.web.exposure.include=*