import React, { useState, useEffect } from 'react';
import { Play, ArrowRight, ArrowLeft, CheckCircle2, XCircle, Award, RotateCcw, HelpCircle, Timer } from 'lucide-react';
import confetti from 'canvas-confetti';
import { getQuizQuestions, submitQuiz } from '../services/api';

export default function QuizPlayer({ quizIdToPlay, onBackToDashboard }) {
  const [quizId, setQuizId] = useState(quizIdToPlay || 1);
  const [questions, setQuestions] = useState([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [userAnswers, setUserAnswers] = useState({});
  const [loading, setLoading] = useState(false);
  const [quizStarted, setQuizStarted] = useState(false);
  const [quizSubmitted, setQuizSubmitted] = useState(false);
  const [score, setScore] = useState(null);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (quizIdToPlay) {
      handleLoadQuiz(quizIdToPlay);
    }
  }, [quizIdToPlay]);

  const handleLoadQuiz = async (targetId) => {
    setLoading(true);
    setQuizSubmitted(false);
    setUserAnswers({});
    setCurrentIndex(0);
    try {
      const qList = await getQuizQuestions(targetId || quizId);
      setQuestions(qList || []);
      setQuizStarted(true);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleSelectOption = (questionId, selectedOption) => {
    setUserAnswers(prev => ({
      ...prev,
      [questionId]: selectedOption
    }));
  };

  const handleSubmitQuiz = async () => {
    setSubmitting(true);
    const responsesPayload = questions.map(q => ({
      id: q.id,
      response: userAnswers[q.id] || ''
    }));

    try {
      const resultScore = await submitQuiz(quizId, responsesPayload);
      setScore(typeof resultScore === 'number' ? resultScore : Number(resultScore) || 0);
      setQuizSubmitted(true);

      // Trigger Confetti if passed (>50%)
      const percentage = (resultScore / (questions.length || 1)) * 100;
      if (percentage >= 50) {
        confetti({
          particleCount: 100,
          spread: 70,
          origin: { y: 0.6 }
        });
      }
    } catch (err) {
      console.error("Submission error:", err);
    } finally {
      setSubmitting(false);
    }
  };

  if (!quizStarted) {
    return (
      <div style={{ maxWidth: '600px', margin: '40px auto' }} className="glass-card">
        <div style={{ padding: '36px', textAlign: 'center' }}>
          <div style={{
            width: '64px',
            height: '64px',
            borderRadius: '20px',
            background: 'var(--accent-gradient)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto 20px',
            boxShadow: 'var(--shadow-glow)'
          }}>
            <HelpCircle size={32} color="#fff" />
          </div>

          <h2 style={{ fontSize: '1.8rem', fontWeight: 800, marginBottom: '10px' }}>
            Ready to Take a <span className="gradient-text">Quiz?</span>
          </h2>
          <p style={{ color: 'var(--text-secondary)', marginBottom: '28px', fontSize: '0.95rem' }}>
            Enter a Quiz ID generated by QuizService or load the default microservices test.
          </p>

          <div style={{ display: 'flex', gap: '12px', justifyContent: 'center', marginBottom: '24px' }}>
            <input
              type="number"
              className="form-input"
              style={{ width: '140px', textAlign: 'center', fontSize: '1.1rem', fontWeight: 700 }}
              value={quizId}
              onChange={(e) => setQuizId(e.target.value)}
              placeholder="Quiz ID"
            />
            <button 
              onClick={() => handleLoadQuiz(quizId)}
              className="btn btn-primary"
              disabled={loading}
            >
              <Play size={18} /> {loading ? 'Loading...' : 'Start Test'}
            </button>
          </div>
        </div>
      </div>
    );
  }

  // Quiz Results View
  if (quizSubmitted) {
    const totalCount = questions.length || 1;
    const percentage = Math.round((score / totalCount) * 100);

    return (
      <div style={{ maxWidth: '750px', margin: '20px auto' }} className="glass-card">
        <div style={{ padding: '40px', textAlign: 'center' }}>
          <div style={{
            width: '80px',
            height: '80px',
            borderRadius: '50%',
            background: percentage >= 50 ? 'rgba(16, 185, 129, 0.15)' : 'rgba(244, 63, 94, 0.15)',
            color: percentage >= 50 ? '#10b981' : '#f43f5e',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto 20px',
            border: `2px solid ${percentage >= 50 ? '#10b981' : '#f43f5e'}`
          }}>
            <Award size={40} />
          </div>

          <h2 style={{ fontSize: '2.2rem', fontWeight: 800, marginBottom: '8px' }}>
            {percentage >= 70 ? '🎉 Excellent Job!' : (percentage >= 50 ? '👍 Good Effort!' : '💪 Keep Practicing!')}
          </h2>
          <p style={{ color: 'var(--text-secondary)', marginBottom: '24px' }}>
            Quiz Evaluation completed by QuestionService microservice.
          </p>

          {/* Score Badge */}
          <div style={{
            background: 'rgba(15, 23, 42, 0.6)',
            padding: '24px',
            borderRadius: '16px',
            border: '1px solid var(--border-subtle)',
            maxWidth: '300px',
            margin: '0 auto 32px'
          }}>
            <div style={{ fontSize: '3rem', fontWeight: 800 }} className="gradient-text">
              {score} / {totalCount}
            </div>
            <div style={{ fontSize: '1rem', color: 'var(--text-muted)', fontWeight: 600 }}>
              Score Percentage: {percentage}%
            </div>
          </div>

          {/* Answers Breakdown */}
          <div style={{ textAlign: 'left', marginBottom: '32px' }}>
            <h4 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '16px', color: 'var(--text-secondary)' }}>
              Answer Breakdown ({questions.length} Questions)
            </h4>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              {questions.map((q, idx) => {
                const selected = userAnswers[q.id];
                return (
                  <div key={q.id} style={{
                    padding: '14px 18px',
                    borderRadius: '10px',
                    background: 'rgba(255,255,255,0.03)',
                    border: '1px solid var(--border-subtle)',
                    display: 'flex',
                    alignItems: 'flex-start',
                    gap: '12px'
                  }}>
                    <span style={{ fontWeight: 700, color: 'var(--text-muted)' }}>#{idx + 1}</span>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontWeight: 600, fontSize: '0.95rem', marginBottom: '4px' }}>{q.questionTitle}</div>
                      <div style={{ fontSize: '0.85rem', color: selected ? 'var(--accent-primary)' : 'var(--text-muted)' }}>
                        Selected: <strong>{selected || 'No Answer'}</strong>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          <div style={{ display: 'flex', gap: '14px', justifyContent: 'center' }}>
            <button 
              onClick={() => handleLoadQuiz(quizId)}
              className="btn btn-secondary"
            >
              <RotateCcw size={16} /> Retake Quiz
            </button>
            <button 
              onClick={onBackToDashboard}
              className="btn btn-primary"
            >
              Back to Dashboard
            </button>
          </div>
        </div>
      </div>
    );
  }

  const currentQ = questions[currentIndex] || {};
  const progressPercent = Math.round(((currentIndex + 1) / questions.length) * 100);

  return (
    <div style={{ maxWidth: '850px', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* Quiz Progress Bar */}
      <div className="glass-card" style={{ padding: '20px 28px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <span className="badge badge-category">Quiz #{quizId}</span>
            <span style={{ fontSize: '0.9rem', fontWeight: 600, color: 'var(--text-secondary)' }}>
              Question {currentIndex + 1} of {questions.length}
            </span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'var(--text-muted)', fontSize: '0.85rem' }}>
            <Timer size={16} /> Microservice Live Assessment
          </div>
        </div>

        <div style={{ height: '8px', background: 'rgba(255,255,255,0.06)', borderRadius: '4px', overflow: 'hidden' }}>
          <div style={{
            height: '100%',
            width: `${progressPercent}%`,
            background: 'var(--accent-gradient)',
            transition: 'width 0.3s ease'
          }} />
        </div>
      </div>

      {/* Question Card */}
      <div className="glass-card" style={{ padding: '36px' }}>
        <h3 style={{ fontSize: '1.35rem', fontWeight: 700, marginBottom: '28px', lineHeight: 1.4 }}>
          {currentQ.questionTitle}
        </h3>

        {/* Options Stack */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', marginBottom: '32px' }}>
          {[currentQ.option1, currentQ.option2, currentQ.option3, currentQ.option4]
            .filter(Boolean)
            .map((opt, oIdx) => {
              const isSelected = userAnswers[currentQ.id] === opt;
              return (
                <div
                  key={oIdx}
                  onClick={() => handleSelectOption(currentQ.id, opt)}
                  style={{
                    padding: '16px 20px',
                    borderRadius: '12px',
                    background: isSelected ? 'rgba(99, 102, 241, 0.18)' : 'rgba(15, 23, 42, 0.6)',
                    border: `1.5px solid ${isSelected ? 'var(--accent-primary)' : 'var(--border-subtle)'}`,
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    transition: 'all 0.2s ease',
                    boxShadow: isSelected ? '0 0 15px rgba(99, 102, 241, 0.2)' : 'none'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
                    <div style={{
                      width: '28px',
                      height: '28px',
                      borderRadius: '50%',
                      border: `2px solid ${isSelected ? 'var(--accent-primary)' : 'var(--text-muted)'}`,
                      background: isSelected ? 'var(--accent-primary)' : 'transparent',
                      color: '#fff',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      fontSize: '0.85rem',
                      fontWeight: 700
                    }}>
                      {String.fromCharCode(65 + oIdx)}
                    </div>
                    <span style={{ fontSize: '1rem', fontWeight: isSelected ? 600 : 400 }}>{opt}</span>
                  </div>

                  {isSelected && <CheckCircle2 size={20} color="var(--accent-primary)" />}
                </div>
              );
            })}
        </div>

        {/* Controls Bar */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingTop: '20px', borderTop: '1px solid var(--border-subtle)' }}>
          <button
            onClick={() => setCurrentIndex(prev => Math.max(0, prev - 1))}
            className="btn btn-secondary"
            disabled={currentIndex === 0}
          >
            <ArrowLeft size={16} /> Previous
          </button>

          {currentIndex < questions.length - 1 ? (
            <button
              onClick={() => setCurrentIndex(prev => Math.min(questions.length - 1, prev + 1))}
              className="btn btn-primary"
            >
              Next <ArrowRight size={16} />
            </button>
          ) : (
            <button
              onClick={handleSubmitQuiz}
              className="btn btn-emerald btn-lg"
              disabled={submitting}
            >
              {submitting ? 'Evaluating Score...' : 'Submit Quiz 🎉'}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
